land_use_dismiss = ['BEACH AREA', 'WATERBODY', 'CEMETERY', 'ROAD', 'WHITE', 'RESERVE SITE', 'OPEN SPACE', 'PARK',
                    'SPECIAL USE']
land_use_rename = {'EDUCATIONAL INSTITUTION': 'EDUCATIONAL',
                   'RESIDENTIAL WITH COMMERCIAL AT 1ST STOREY': 'COMMERCIAL & RESIDENTIAL', 'BUSINESS 1': 'INDUSTRIAL',
                   'BUSINESS 2': 'INDUSTRIAL', 'BUSINESS 1 - WHITE': 'INDUSTRIAL', 'BUSINESS 2 - WHITE': 'INDUSTRIAL',
                   'RESIDENTIAL / INSTITUTION': 'RESIDENTIAL', 'COMMERCIAL / INSTITUTION': 'COMMERCIAL',
                   'AGRICULTURE': 'INDUSTRIAL', 'TRANSPORT FACILITIES': 'TRANSPORT',
                   'MASS RAPID TRANSIT': 'TRANSPORT', 'LIGHT RAPID TRANSIT': 'TRANSPORT', 'HOTEL': 'COMMERCIAL',
                   'UTILITY': 'INDUSTRIAL', 'BUSINESS PARK - WHITE': 'COMMERCIAL', 'BUSINESS PARK': 'COMMERCIAL',
                   'PLACE OF WORSHIP': 'CIVIC & COMMUNITY INSTITUTION',
                   'PORT / AIRPORT': 'TRANSPORT', 'HEALTH & MEDICAL CARE': 'CIVIC & COMMUNITY INSTITUTION'}
