reqd = ['amenity', 'shop', 'tourism', 'healthcare', 'office', 'leisure', 'sport']
use_tags = ['name', 'amenity', 'shop', 'tourism', 'healthcare', 'office', 'leisure', 'sport', 'building']
polyline_forbid = ['cycleway', "footway", "steps"]
building_rqd = ['amenity', 'healthcare', 'office', 'shop']
building = 'building'
polygon = 'polygon'
building_forbid = ['roof', 'yes', 'garage', 'terrace', 'shed']
building_others = ['parking_space', 'toilets']
polyline_ms = 'maxspeed'
negative_reqd = ['bench', 'loading_dock', 'drinking_water', 'waste_basket', 'outdoor_seating', 'recycling', 'bicycle_parking', 'parking_entrance', 'bicycle_parking', 'charging_station', 'toilets', 'fountain']
dd = ['name', 'created_by', 'entrance', 'junction', 'aeroway', 'noexit', 'source', 'note', 'man_made', 'ref', 'mapillary', 'image', 'incline', 'operator', 'bicycle', 'foot', 'waterway', 'access', 'crossing', 'tactile_paving', 'level', 'door', 'node']
cont_dd = ['addr', 'aero', 'seamark']
int_routes = ['bus']
perm_dd = 'disused'
polyline_hw = {'primary': 0, 'secondary': 1, 'tertiary': 2, 'motorway': 3, 'residential': 4, 'trunk': 5, 'service': 6, 'default': 7}
polyline_ow = {'yes': 0, 'no': 1, 'default': 2}
polyline_hw_default = 'default'
hw_emb = 8
lane_emb = 6
ow_emb = 3
ms_emb = 11
